name: Python Test'n'lint

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'animations/**'
      - '.github/workflows/web.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          ./go init
      - name: Lint
        run: |
          ./go lint

