name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "led-art-box"
          heroku_email: "stefanie.grewenig@googlemail.com"