name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web